# Generated by Django 6.0.6 on 2026-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_index', models.IntegerField(unique=True)),
                ('publishing_year', models.IntegerField(blank=True, null=True)),
                ('book_name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('language_code', models.CharField(blank=True, default='Unknown', max_length=20)),
                ('author_rating', models.CharField(choices=[('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Excellent', 'Excellent'), ('Famous', 'Famous')], max_length=20)),
                ('book_average_rating', models.FloatField()),
                ('book_ratings_count', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
